language: c
os: [osx, linux]
osx_image: xcode9.3
sudo: true
addons:
  apt:
    packages:
      - gawk
      - libgmp-dev
before_install:
  - rm ~/.rvm/hooks/after_use
  - "sed -i'' -e '/rvm_project_rvmrc/d ; /rvm_silence_path_mismatch_check_flag/d' ~/.rvmrc || true"
  - "echo rvm_show_log_lines_on_error=all >> ~/.rvmrc"
  - "head -n 100 /etc/rvmrc ~/.rvmrc || true"
  - rvm list
  - "rvm use ruby-2.4 --fuzzy || rvm use ruby-2.3 --fuzzy"
  - "[[ -n \"${LANG:-}\" ]] || export LANG=en_US.UTF-8"
  - "env | grep '^rvm' || true"
install:
  - gem install tf -v '>=0.4.1'
before_script:
  - "echo ruby_1.8.7_rubygems_version=1.8.25 > $rvm_path/user/db"
  - "if [[ -f ~/.rvmrc ]] ; then sed -i'' -r -e '/rvm_silence_path_mismatch_check_flag|rvm_project_rvmrc/ d' ~/.rvmrc ; fi"
  - unset rvm_silence_path_mismatch_check_flag rvm_project_rvmrc
  - rvm alias delete default
  - hash -r
  - ./install
  - rvm reload
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm autolibs read-only; fi
script:
  - tf --text $TEST
env:
  - TEST=rvm-test/fast/* rvm-test-rvm1/*
  - TEST=rvm-test/long/named_ruby_and_gemsets_comment_test.sh
  - TEST=rvm-test/long/truffleruby_comment_test.sh
matrix:
  include:
    - os: linux
      env: TEST="rvm-installer GPG signature"
      addons:
        apt:
          packages:
            - dirmngr
            - gnupg2
      script:
        - gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
        - gpg2 --verify binscripts/rvm-installer.asc binscripts/rvm-installer
    - language: ruby
      os: linux
      env: TEST="Test TruffleRuby in TravisCI"
      rvm: truffleruby
      before_install: true
      install: true
      before_script: true
      script:
        - ruby -v
        - rake --version
        - ruby -S bundle --version
        - ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
